// The ONE place in application code that reads `process.env`. Everything else takes
// configuration as a value, so a missing key is a boot failure naming the key rather
// than an `undefined` that surfaces as a wrong figure hours later.
//
// ESLint's environment ban (see eslint.config.js) exempts exactly this file and
// `**/*.test.ts` — the test exemption is forced by an existing test that reads
// `process.env.REQUIRE_DB`, and is recorded in deferred-work.md. The clock adapter is NOT
// exempt from it: the two bans are switched independently, so each sanctioned home is still
// fenced in the direction it has no business going. This file, in turn, is still forbidden
// to read the wall clock. Adding a second environment reader in application code is a lint
// error, by design.
//
// The schema is deliberately thin — two connection strings, and they are two on purpose:
//
//   * DATABASE_URL names the owning role. It is what `drizzle-kit`, the seed, the scripts
//     and (today) every application read connect as, and it is the role the pg-boss
//     migrator step assumes ownership from.
//   * APP_DATABASE_URL names the restricted `app` role, which holds DML on the `pgboss`
//     schema and nothing else — no `CREATE`, so pg-boss's own DDL would be refused rather
//     than performed. Only `apps/worker` uses it. It deliberately does NOT take over the
//     existing connection: the app role's table grants are generated by story 1.2's
//     table-class registry and do not exist yet, so pointing web, seed, scripts or the
//     tests at it would leave them with no access to any application table.
//
// Later stories extend this schema (session idle timeout, mail transport, the fixture-mode
// clock anchor) by adding keys here — never by reading the environment somewhere else.
import { z } from 'zod';

const configSchema = z.object({
  DATABASE_URL: z
    .string({
      error:
        'is required — the PostgreSQL connection string, e.g. postgres://user:pass@host:port/db',
    })
    .min(1, 'must not be empty — it is the PostgreSQL connection string'),

  // The worker connects as this role and pg-boss is constructed with `migrate: false` and
  // `createSchema: false`, so the role needs no DDL rights at all. Its user and password
  // are also what the migrator step creates the role from, which is why one string carries
  // the whole identity rather than a name and a password drifting apart in two keys.
  APP_DATABASE_URL: z
    .string({
      error:
        'is required — the PostgreSQL connection string for the restricted application role, e.g. postgres://momo_app:momo_app@host:port/db',
    })
    .min(1, 'must not be empty — it is the restricted application role connection string'),
});

export type AppConfig = z.infer<typeof configSchema>;

/**
 * Parses a raw environment into the application configuration.
 *
 * Throws naming every offending key. Takes the environment as an argument so the
 * parse is a pure function of its input and can be exercised without mutating the
 * real process environment.
 */
export function parseConfig(env: Record<string, string | undefined>): AppConfig {
  const result = configSchema.safeParse(env);
  if (result.success) return result.data;

  const named = result.error.issues
    .map((issue) => `${issue.path.join('.') || '(root)'} ${issue.message}`)
    .join('; ');
  throw new Error(`Invalid configuration: ${named}`);
}

/**
 * Parsed once, at module load, so boot fails at the boundary instead of at the first
 * query. Importing this module in a process without the required keys is meant to
 * throw.
 */
export const config: AppConfig = parseConfig(process.env);
