import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import pg from 'pg';
import { getTableConfig } from 'drizzle-orm/pg-core';
import { buildDemoState } from './fixtures';
import * as schemaModule from './schema';
import { FK_DEFERRABLE, FK_MATCH_SIMPLE } from './schema';
import { acquireSeedSuiteLock, releaseSeedSuiteLock } from './seed-suite-lock';
import { TENANT_OWNED } from './table-classes';

/**
 * THE CATALOGUE GATE ON STORY 2.1's MIGRATION (AD-30).
 *
 * `packages/db/drizzle/0000_*.sql` carries clauses drizzle-kit 0.31.10 does not emit — `MATCH
 * FULL`, and `DEFERRABLE INITIALLY DEFERRED` on `wp_dependency`'s two leaf FKs — plus one it does
 * emit but PostgreSQL 18 would silently change the meaning of if it were lost (`STORED` on
 * `is_leaf`). A later schema edit regenerated by drizzle-kit drops the hand-written ones without a
 * word, so each is read back from the live catalogue here and a lost one fails NAMING the
 * constraint or column:
 *
 *   * every foreign key Drizzle declares exists, and no other does;
 *   * `pg_constraint.confmatchtype` is 's' for the nullable-member FKs (`FK_MATCH_SIMPLE`,
 *     decision 3-A) and 'f' for every other one;
 *   * `condeferrable`/`condeferred` are true on exactly `FK_DEFERRABLE`;
 *   * every FK is `ON DELETE / ON UPDATE NO ACTION` (Plan deletion is soft);
 *   * every FK from a tenant-owned table is composite and includes `tenant_id` on both sides;
 *   * `work_package.is_leaf` has `attgenerated = 's'`, and the four dropped columns are gone.
 *
 * Then the I/O matrix of the story's spec, each case as a real statement against the real schema:
 * the cross-tenant child and the summary endpoint (23503, the latter at COMMIT), a mid-transaction
 * re-parent that commits, and the two CHECKs (23514).
 *
 * Runs as the OWNER (DATABASE_URL). Every probe row it writes sets `app.tenant_id` first, so it
 * does not depend on the owner being a superuser that bypasses row-level security.
 */

const REQUIRE_DB = process.env.REQUIRE_DB === '1';
const OWNER_DATABASE_URL = process.env.DATABASE_URL;

if (REQUIRE_DB && !OWNER_DATABASE_URL) {
  throw new Error(
    'REQUIRE_DB=1 but DATABASE_URL is not set. This file is the gate on the hand-written clauses ' +
      'of the AD-30 migration, so it must not be skipped.',
  );
}

async function reachableAs(connectionString: string | undefined): Promise<boolean> {
  if (!connectionString) return false;
  const client = new pg.Client({ connectionString, application_name: 'momo-catalog-test' });
  try {
    await client.connect();
    return true;
  } catch {
    return false;
  } finally {
    await client.end().catch(() => {});
  }
}

const reachable = await reachableAs(OWNER_DATABASE_URL);

if (REQUIRE_DB && !reachable) {
  throw new Error('REQUIRE_DB=1 but the database is not reachable. Run `pnpm db:migrate` first.');
}

// The matrix writes short-lived probe Tenants, so this is a probe suite: it holds the seed-suite
// lock shared, and a seed's single-Tenant guard never counts its rows (`seed-suite-lock.ts`).
if (reachable) {
  await acquireSeedSuiteLock(OWNER_DATABASE_URL!, 'shared');
}

async function asOwner<T>(work: (client: pg.Client) => Promise<T>): Promise<T> {
  const client = new pg.Client({
    connectionString: OWNER_DATABASE_URL,
    application_name: 'momo-catalog-test-owner',
  });
  await client.connect();
  try {
    return await work(client);
  } finally {
    await client.end();
  }
}

/** The SQLSTATE of a rejected statement, or undefined when it was not rejected. */
async function refusalCode(work: Promise<unknown>): Promise<string | undefined> {
  try {
    await work;
    return undefined;
  } catch (error) {
    const code = (error as { code?: unknown }).code;
    return typeof code === 'string' ? code : 'not-a-pg-error';
  }
}

/** Every foreign key the Drizzle schema declares, by name, with its child table. */
function declaredForeignKeys(): { name: string; table: string }[] {
  return Object.values(schemaModule.schemaTables).flatMap((table) => {
    const config = getTableConfig(table);
    return config.foreignKeys.map((fk) => ({ name: fk.getName(), table: config.name }));
  });
}

interface ForeignKeyRow {
  readonly conname: string;
  readonly child: string;
  readonly parent: string;
  readonly confmatchtype: string;
  readonly condeferrable: boolean;
  readonly condeferred: boolean;
  readonly confdeltype: string;
  readonly confupdtype: string;
  readonly child_columns: string[];
  readonly parent_columns: string[];
}

async function readForeignKeys(): Promise<ForeignKeyRow[]> {
  return asOwner(async (client) => {
    const { rows } = await client.query<ForeignKeyRow>(
      `SELECT con.conname,
              child.relname AS child,
              parent.relname AS parent,
              con.confmatchtype::text AS confmatchtype,
              con.condeferrable,
              con.condeferred,
              con.confdeltype::text AS confdeltype,
              con.confupdtype::text AS confupdtype,
              ARRAY(SELECT a.attname::text FROM unnest(con.conkey) WITH ORDINALITY k(attnum, ord)
                      JOIN pg_catalog.pg_attribute a
                        ON a.attrelid = con.conrelid AND a.attnum = k.attnum
                     ORDER BY k.ord) AS child_columns,
              ARRAY(SELECT a.attname::text FROM unnest(con.confkey) WITH ORDINALITY k(attnum, ord)
                      JOIN pg_catalog.pg_attribute a
                        ON a.attrelid = con.confrelid AND a.attnum = k.attnum
                     ORDER BY k.ord) AS parent_columns
         FROM pg_catalog.pg_constraint con
         JOIN pg_catalog.pg_class child ON child.oid = con.conrelid
         JOIN pg_catalog.pg_class parent ON parent.oid = con.confrelid
         JOIN pg_catalog.pg_namespace n ON n.oid = child.relnamespace
        WHERE con.contype = 'f' AND n.nspname = 'public'
        ORDER BY con.conname`,
    );
    return rows;
  });
}

afterAll(async () => {
  if (reachable) await asOwner(removeMatrixTenants);
  await releaseSeedSuiteLock();
});

describe.skipIf(!reachable)('the hand-written clauses of the AD-30 migration are in the catalogue', () => {
  let fks: ForeignKeyRow[] = [];
  beforeAll(async () => {
    fks = await readForeignKeys();
  });

  it('holds exactly the foreign keys schema.ts declares', () => {
    const declared = declaredForeignKeys().map((fk) => fk.name).sort();
    const live = fks.map((fk) => fk.conname).sort();
    expect(
      declared.filter((name) => !live.includes(name)),
      'these foreign keys are declared in schema.ts but missing from the database — was the ' +
        'migration regenerated without them, or not applied (`pnpm db:migrate`)?',
    ).toEqual([]);
    expect(
      live.filter((name) => !declared.includes(name)),
      'these foreign keys exist in the database but schema.ts does not declare them',
    ).toEqual([]);
    // Sanity: the lists the migration's hand edits were made from name real constraints.
    for (const name of [...FK_MATCH_SIMPLE, ...FK_DEFERRABLE]) {
      expect(declared, `${name} is listed in schema.ts but declared nowhere`).toContain(name);
    }
  });

  it('is MATCH FULL on every foreign key but the nullable-member ones, which are MATCH SIMPLE (3-A)', () => {
    const wrong = fks
      .map((fk) => ({ fk, want: FK_MATCH_SIMPLE.includes(fk.conname) ? 's' : 'f' }))
      .filter(({ fk, want }) => fk.confmatchtype !== want)
      .map(
        ({ fk, want }) =>
          `${fk.conname}: confmatchtype '${fk.confmatchtype}', expected '${want}' (` +
          `${want === 'f' ? 'MATCH FULL' : 'MATCH SIMPLE'})`,
      );
    expect(
      wrong,
      'a regeneration dropped a hand-written match type; restore it in packages/db/drizzle/0000_*.sql',
    ).toEqual([]);
  });

  it('defers exactly wp_dependency\'s two leaf foreign keys (condeferrable, INITIALLY DEFERRED)', () => {
    const wrong = fks
      .filter((fk) => {
        const want = FK_DEFERRABLE.includes(fk.conname);
        return fk.condeferrable !== want || fk.condeferred !== want;
      })
      .map(
        (fk) =>
          `${fk.conname}: condeferrable=${fk.condeferrable}, condeferred=${fk.condeferred}, ` +
          `expected ${FK_DEFERRABLE.includes(fk.conname)}`,
      );
    expect(wrong).toEqual([]);
    expect(FK_DEFERRABLE).toEqual(['wp_dependency_predecessor_fk', 'wp_dependency_successor_fk']);
  });

  it('is ON DELETE and ON UPDATE NO ACTION everywhere — Plan deletion is soft', () => {
    const wrong = fks
      .filter((fk) => fk.confdeltype !== 'a' || fk.confupdtype !== 'a')
      .map((fk) => `${fk.conname}: delete '${fk.confdeltype}', update '${fk.confupdtype}'`);
    expect(wrong).toEqual([]);
  });

  it('makes every tenant-owned foreign key composite and tenant_id-led on both sides (AD-3)', () => {
    const tenantOwned = new Map(TENANT_OWNED.map((e) => [e.table, e.tenantColumn!]));
    const wrong = fks
      .filter((fk) => tenantOwned.has(fk.child))
      .filter(
        (fk) =>
          fk.child_columns.length < 2 ||
          fk.child_columns[0] !== tenantOwned.get(fk.child) ||
          fk.parent_columns[0] !== tenantOwned.get(fk.parent),
      )
      .map((fk) => `${fk.conname}: (${fk.child_columns.join(', ')}) → ${fk.parent}(${fk.parent_columns.join(', ')})`);
    expect(wrong).toEqual([]);
    // And no tenant-owned child points at a table that is not tenant-owned.
    expect(fks.filter((fk) => tenantOwned.has(fk.child) && !tenantOwned.has(fk.parent))).toEqual([]);
  });

  it('covers the seven relationships the Epic 1 audit named as unprotected', () => {
    const edges = new Set(fks.map((fk) => `${fk.child} → ${fk.parent}`));
    for (const edge of [
      'project → department',
      'project → program',
      'program → department',
      'work_package → project',
      'baseline_wp → work_package',
      'rate_entry → resource',
      'mapping_event → work_package',
    ]) {
      expect(edges, `no foreign key for ${edge}`).toContain(edge);
    }
  });

  it('stores is_leaf as a STORED generated column (attgenerated = \'s\')', async () => {
    const rows = await asOwner(async (client) => {
      const { rows } = await client.query<{ attgenerated: string }>(
        `SELECT a.attgenerated::text AS attgenerated
           FROM pg_catalog.pg_attribute a
           JOIN pg_catalog.pg_class c ON c.oid = a.attrelid
           JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
          WHERE n.nspname = 'public' AND c.relname = 'work_package' AND a.attname = 'is_leaf'`,
      );
      return rows;
    });
    expect(rows, 'work_package.is_leaf does not exist').toHaveLength(1);
    expect(
      rows[0]!.attgenerated,
      "work_package.is_leaf must be GENERATED ALWAYS AS (child_count = 0) STORED; 'v' is " +
        'PostgreSQL 18\'s VIRTUAL default, which cannot be a UNIQUE member or an FK target',
    ).toBe('s');
  });

  it('has dropped work_package.start, finish, completed_at and milestone_done_at', async () => {
    const columns = await asOwner(async (client) => {
      const { rows } = await client.query<{ column_name: string }>(
        `SELECT column_name FROM information_schema.columns
          WHERE table_schema = 'public' AND table_name = 'work_package'`,
      );
      return rows.map((row) => row.column_name);
    });
    for (const dropped of ['start', 'finish', 'completed_at', 'milestone_done_at']) {
      expect(columns, `work_package.${dropped} still exists`).not.toContain(dropped);
    }
    for (const added of ['duration_days', 'constraint_type', 'constraint_date', 'child_count', 'is_leaf']) {
      expect(columns, `work_package.${added} is missing`).toContain(added);
    }
  });
});

// ---------------------------------------------------------------------------------------------
// The I/O matrix. Two short-lived probe Tenants, removed before and after.

const TENANT_X = 'ten-catalog-x';
const TENANT_Y = 'ten-catalog-y';
const MATRIX_TENANTS = [TENANT_X, TENANT_Y];

async function setTenant(client: pg.Client, tenantId: string): Promise<void> {
  await client.query(`SELECT set_config('app.tenant_id', $1, true)`, [tenantId]);
}

/** A Tenant with one Department and one Project, inside the caller's transaction. */
async function writeTenantShell(client: pg.Client, tenantId: string): Promise<string> {
  const projectId = `${tenantId}-prj`;
  await client.query('INSERT INTO tenant (id, name) VALUES ($1, $1)', [tenantId]);
  await setTenant(client, tenantId);
  await client.query('INSERT INTO department (id, tenant_id, name) VALUES ($1, $2, $1)', [
    `${tenantId}-dep`,
    tenantId,
  ]);
  await client.query(
    `INSERT INTO project (id, tenant_id, department_id, name, client_name, contract_type,
       tz_offset_minutes, teirei_weekday, default_rate_jpy, eac_method, calendar_jp, calendar_vn,
       demo_anchor)
     VALUES ($1, $2, $3, $1, 'client', '請負', 540, 1, 0, 'typical', true, false,
       '2026-09-16T09:00:00Z')`,
    [projectId, tenantId, `${tenantId}-dep`],
  );
  return projectId;
}

/** Inserts one Work Package; `childCount > 0` makes it a summary. */
async function writeWp(
  client: pg.Client,
  tenantId: string,
  projectId: string,
  id: string,
  extra: {
    parentId?: string;
    childCount?: number;
    durationDays?: number;
    constraintType?: string;
    constraintDate?: string;
  } = {},
): Promise<void> {
  await client.query(
    `INSERT INTO work_package (id, tenant_id, project_id, wbs_code, name, parent_id, child_count,
       is_milestone, is_catch_all, duration_days, constraint_type, constraint_date, planned_mh,
       assigned_resource_ids)
     VALUES ($1, $2, $3, $1, $1, $4, $5, false, false, $6, $7, $8, 0, '{}')`,
    [
      id,
      tenantId,
      projectId,
      extra.parentId ?? null,
      extra.childCount ?? 0,
      extra.durationDays ?? null,
      extra.constraintType ?? 'asap',
      extra.constraintDate ?? null,
    ],
  );
}

/** Removes both matrix Tenants' rows, children first. Idempotent. */
async function removeMatrixTenants(client: pg.Client): Promise<void> {
  for (const tenantId of MATRIX_TENANTS) {
    await client.query('BEGIN');
    try {
      await setTenant(client, tenantId);
      for (const table of ['wp_dependency', 'work_package', 'project', 'department']) {
        await client.query(`DELETE FROM ${table} WHERE tenant_id = $1`, [tenantId]);
      }
      await client.query('DELETE FROM tenant WHERE id = $1', [tenantId]);
      await client.query('COMMIT');
    } catch (error) {
      await client.query('ROLLBACK');
      throw error;
    }
  }
}

/** Runs `work` in a transaction that is always rolled back, returning its refusal code. */
async function refusedInRolledBackTx(
  work: (client: pg.Client) => Promise<unknown>,
): Promise<string | undefined> {
  return asOwner(async (client) => {
    await client.query('BEGIN');
    try {
      return await refusalCode(work(client));
    } finally {
      await client.query('ROLLBACK');
    }
  });
}

describe.skipIf(!reachable)('the I/O matrix of story 2.1, against the migrated schema', () => {
  beforeAll(async () => {
    await asOwner(removeMatrixTenants);
  });

  it('rejects a Work Package whose (tenant_id, project_id) names another Tenant\'s Project (23503)', async () => {
    const code = await refusedInRolledBackTx(async (client) => {
      const projectOfX = await writeTenantShell(client, TENANT_X);
      await writeTenantShell(client, TENANT_Y);
      await setTenant(client, TENANT_Y);
      await writeWp(client, TENANT_Y, projectOfX, 'wp-catalog-cross');
    });
    expect(code).toBe('23503');
  });

  it('rejects a dependency on a summary Work Package at COMMIT, not at the statement (23503)', async () => {
    const outcome = await asOwner(async (client) => {
      await client.query('BEGIN');
      try {
        const projectId = await writeTenantShell(client, TENANT_X);
        await writeWp(client, TENANT_X, projectId, 'wp-cat-summary', { childCount: 1 });
        await writeWp(client, TENANT_X, projectId, 'wp-cat-child', { parentId: 'wp-cat-summary' });
        await writeWp(client, TENANT_X, projectId, 'wp-cat-leaf');
        // Accepted here: the leaf FKs are DEFERRABLE INITIALLY DEFERRED.
        await client.query(
          `INSERT INTO wp_dependency (tenant_id, project_id, predecessor_wp_id, successor_wp_id)
           VALUES ($1, $2, 'wp-cat-summary', 'wp-cat-leaf')`,
          [TENANT_X, projectId],
        );
      } catch (error) {
        await client.query('ROLLBACK');
        return { statement: (error as { code?: string }).code ?? 'unknown', commit: undefined };
      }
      return { statement: undefined, commit: await refusalCode(client.query('COMMIT')) };
    });
    expect(outcome.statement, 'the insert itself was refused — the FK is not deferred').toBeUndefined();
    expect(outcome.commit).toBe('23503');
    // Nothing of the transaction landed.
    await asOwner(removeMatrixTenants);
  });

  it('commits an edge added before its endpoint\'s child_count is fixed in the same transaction', async () => {
    const code = await asOwner(async (client) => {
      await client.query('BEGIN');
      const projectId = await writeTenantShell(client, TENANT_X);
      // `wp-cat-a` starts as a summary (child_count 1) with no child yet — the middle of a re-parent.
      await writeWp(client, TENANT_X, projectId, 'wp-cat-a', { childCount: 1 });
      await writeWp(client, TENANT_X, projectId, 'wp-cat-b');
      await client.query(
        `INSERT INTO wp_dependency (tenant_id, project_id, predecessor_wp_id, successor_wp_id)
         VALUES ($1, $2, 'wp-cat-a', 'wp-cat-b')`,
        [TENANT_X, projectId],
      );
      await client.query(`UPDATE work_package SET child_count = 0 WHERE id = 'wp-cat-a'`);
      return refusalCode(client.query('COMMIT'));
    });
    await asOwner(removeMatrixTenants);
    expect(code, 'the re-parent was judged before COMMIT').toBeUndefined();
  });

  it('rejects a summary Work Package that carries a duration (23514)', async () => {
    const code = await refusedInRolledBackTx(async (client) => {
      const projectId = await writeTenantShell(client, TENANT_X);
      await writeWp(client, TENANT_X, projectId, 'wp-cat-dur', { childCount: 1, durationDays: 3 });
    });
    expect(code).toBe('23514');
  });

  it('rejects a summary Work Package that carries a constraint (23514)', async () => {
    const code = await refusedInRolledBackTx(async (client) => {
      const projectId = await writeTenantShell(client, TENANT_X);
      await writeWp(client, TENANT_X, projectId, 'wp-cat-cons', {
        childCount: 1,
        constraintType: 'must_finish_on',
        constraintDate: '2027-03-18',
      });
    });
    expect(code).toBe('23514');
  });

  it('rejects a summary Work Package that carries a constraint date under asap (23514)', async () => {
    const code = await refusedInRolledBackTx(async (client) => {
      const projectId = await writeTenantShell(client, TENANT_X);
      await writeWp(client, TENANT_X, projectId, 'wp-cat-cdate', {
        childCount: 1,
        constraintType: 'asap',
        constraintDate: '2027-03-18',
      });
    });
    expect(code).toBe('23514');
  });

  it('rejects a dependency type other than FS (23514)', async () => {
    const code = await refusedInRolledBackTx(async (client) => {
      const projectId = await writeTenantShell(client, TENANT_X);
      await writeWp(client, TENANT_X, projectId, 'wp-cat-p');
      await writeWp(client, TENANT_X, projectId, 'wp-cat-s');
      await client.query(
        `INSERT INTO wp_dependency (tenant_id, project_id, predecessor_wp_id, successor_wp_id, type)
         VALUES ($1, $2, 'wp-cat-p', 'wp-cat-s', 'SS')`,
        [TENANT_X, projectId],
      );
    });
    expect(code).toBe('23514');
  });
});

// ---------------------------------------------------------------------------------------------
// What the seed wrote into `wp_status_event`, the single home of actual dates (AD-25).

describe.skipIf(!reachable)('the demo seed\'s actual dates (story 2.1)', () => {
  it('records exactly one wp_status_event per fixture milestone reached, with its done date', async () => {
    const state = buildDemoState();
    const tenantId = state.fixture.tenant.id;
    const expected = state.wps
      .filter((w) => w.milestoneDoneAt !== null)
      .map((w) => ({ wp_id: w.id, actual_finish: w.milestoneDoneAt }))
      .sort((a, b) => a.wp_id.localeCompare(b.wp_id));
    expect(expected.length, 'the fixture must carry reached milestones').toBeGreaterThan(0);

    const rows = await asOwner(async (client) => {
      await client.query('BEGIN');
      try {
        await setTenant(client, tenantId);
        const { rows } = await client.query<{ wp_id: string; actual_finish: string }>(
          `SELECT wp_id, to_char(actual_finish, 'YYYY-MM-DD') AS actual_finish
             FROM wp_status_event WHERE tenant_id = $1 ORDER BY wp_id`,
          [tenantId],
        );
        return rows;
      } finally {
        await client.query('ROLLBACK');
      }
    });
    expect(rows).toEqual(expected);
  });
});
