-- AD-30: THE ONE PRE-PRODUCTION MIGRATION (story 2.1). It is the whole schema: the Epic 1
-- tables with their composite (tenant_id, ...) foreign keys, plus the scheduling slice (AR-59).
-- From the next migration onward AD-19's expand/contract discipline binds; this exemption is spent.
-- A Baseline written before this migration is deleted, not migrated: there is none to carry over,
-- because this file creates the schema from nothing.
--
-- Generated by `drizzle-kit generate` (0.31.10) from packages/db/src/schema.ts and
-- schema-membership.ts, then HAND-EDITED in exactly these ways, each pinned against the catalogue
-- by packages/db/src/schema-catalog.test.ts so a regeneration that loses one fails naming it:
--
--   1. `MATCH FULL` added to every composite foreign key whose columns are all NOT NULL
--      (pg_constraint.confmatchtype = 'f').
--   2. `MATCH SIMPLE` written explicitly on the seven foreign keys with a nullable member column
--      (founder decision 3-A; schema.ts FK_MATCH_SIMPLE): project_program_fk,
--      work_package_parent_fk, schedule_run_prev_run_fk, actuals_ledger_entry_baseline_version_fk,
--      mapping_event_work_package_fk, mapping_event_mapping_rule_fk,
--      disposition_event_work_package_fk (confmatchtype = 's'). This is PostgreSQL's default, so
--      it changes nothing; it is written so the choice is visible where the others are made.
--   3. `DEFERRABLE INITIALLY DEFERRED` added to wp_dependency_predecessor_fk and
--      wp_dependency_successor_fk (AD-25; condeferrable and condeferred both true).
--
-- The third clause AD-30 names, `is_leaf ... GENERATED ALWAYS AS (child_count = 0) STORED`, was
-- emitted by drizzle-kit itself and needed no edit; it is asserted all the same
-- (pg_attribute.attgenerated = 's'), because PostgreSQL 18 defaults a generated column to VIRTUAL.
--
-- Nothing else here is hand-written. The row-level security, grants and append-only triggers are
-- generated from packages/db/src/table-classes.ts and applied by `pnpm db:policies`.
CREATE TABLE "account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp with time zone,
	"refresh_token_expires_at" timestamp with time zone,
	"scope" text,
	"password" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "actuals_ledger_entry" (
	"seq" bigint PRIMARY KEY NOT NULL,
	"id" text NOT NULL,
	"tenant_id" text NOT NULL,
	"connector_id" text NOT NULL,
	"ticket_id" text NOT NULL,
	"kind" text NOT NULL,
	"delta_mh" bigint NOT NULL,
	"window_start" timestamp with time zone,
	"window_end" timestamp with time zone NOT NULL,
	"assignee_account_id" text,
	"active_baseline_version_seq" bigint,
	"snapshot_id" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "audit_log" (
	"seq" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "audit_log_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" text NOT NULL,
	"actor" text NOT NULL,
	"action" text NOT NULL,
	"target" text NOT NULL,
	"payload" jsonb,
	"at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "auth_user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean DEFAULT false NOT NULL,
	"image" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"locale" text DEFAULT 'en' NOT NULL,
	CONSTRAINT "auth_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "baseline_version" (
	"seq" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "baseline_version_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text NOT NULL,
	"tenant_id" text NOT NULL,
	"project_id" text NOT NULL,
	"schedule_run_seq" bigint NOT NULL,
	"reason" text NOT NULL,
	"recorded_at" timestamp with time zone NOT NULL,
	"actor" text NOT NULL,
	CONSTRAINT "baseline_version_tenant_seq_key" UNIQUE("tenant_id","seq"),
	CONSTRAINT "baseline_version_project_seq_key" UNIQUE("tenant_id","project_id","seq")
);
--> statement-breakpoint
CREATE TABLE "baseline_wp" (
	"id" text PRIMARY KEY NOT NULL,
	"tenant_id" text NOT NULL,
	"project_id" text NOT NULL,
	"baseline_version_seq" bigint NOT NULL,
	"wp_id" text NOT NULL,
	"wp_is_leaf" boolean DEFAULT true NOT NULL,
	"start" date NOT NULL,
	"finish" date NOT NULL,
	"baseline_mh" bigint NOT NULL,
	"is_milestone" boolean NOT NULL,
	"is_catch_all" boolean NOT NULL,
	CONSTRAINT "baseline_wp_version_wp_key" UNIQUE("tenant_id","baseline_version_seq","wp_id"),
	CONSTRAINT "baseline_wp_wp_is_leaf_check" CHECK ("baseline_wp"."wp_is_leaf" = true)
);
--> statement-breakpoint
CREATE TABLE "connector" (
	"id" text PRIMARY KEY NOT NULL,
	"tenant_id" text NOT NULL,
	"project_id" text NOT NULL,
	"adapter" text NOT NULL,
	"scope" text NOT NULL,
	"space_label" text NOT NULL,
	CONSTRAINT "connector_tenant_id_key" UNIQUE("tenant_id","id")
);
--> statement-breakpoint
CREATE TABLE "department" (
	"id" text PRIMARY KEY NOT NULL,
	"tenant_id" text NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "department_tenant_id_key" UNIQUE("tenant_id","id")
);
--> statement-breakpoint
CREATE TABLE "disposition_event" (
	"seq" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "disposition_event_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text NOT NULL,
	"tenant_id" text NOT NULL,
	"project_id" text NOT NULL,
	"kind" text NOT NULL,
	"ticket_ids" text[] NOT NULL,
	"wp_id" text,
	"note" text,
	"at" timestamp with time zone NOT NULL,
	"actor" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "holiday_calendar_version" (
	"seq" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "holiday_calendar_version_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" text NOT NULL,
	"project_id" text NOT NULL,
	"non_working_days" date[] NOT NULL,
	"range_start" date NOT NULL,
	"range_end" date NOT NULL,
	"national_sets" text[] NOT NULL,
	"national_dataset_version" text NOT NULL,
	"reason" text,
	"actor" text NOT NULL,
	"at" timestamp with time zone NOT NULL,
	CONSTRAINT "holiday_calendar_version_project_seq_key" UNIQUE("tenant_id","project_id","seq"),
	CONSTRAINT "holiday_calendar_version_range_check" CHECK ("holiday_calendar_version"."range_start" <= "holiday_calendar_version"."range_end")
);
--> statement-breakpoint
CREATE TABLE "identity_event" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"action" text NOT NULL,
	"at" timestamp with time zone NOT NULL,
	"payload" jsonb
);
--> statement-breakpoint
CREATE TABLE "mapping_event" (
	"seq" bigint PRIMARY KEY NOT NULL,
	"id" text NOT NULL,
	"tenant_id" text NOT NULL,
	"project_id" text NOT NULL,
	"ticket_id" text NOT NULL,
	"wp_id" text,
	"source" text NOT NULL,
	"rule_id" text,
	"at" timestamp with time zone NOT NULL,
	"actor" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "mapping_rule" (
	"id" text PRIMARY KEY NOT NULL,
	"tenant_id" text NOT NULL,
	"project_id" text NOT NULL,
	"priority" integer NOT NULL,
	"name" text NOT NULL,
	"wp_id" text NOT NULL,
	"match_field" text NOT NULL,
	"match_value" text NOT NULL,
	CONSTRAINT "mapping_rule_tenant_project_id_key" UNIQUE("tenant_id","project_id","id")
);
--> statement-breakpoint
CREATE TABLE "program" (
	"id" text PRIMARY KEY NOT NULL,
	"tenant_id" text NOT NULL,
	"department_id" text NOT NULL,
	"name" text NOT NULL,
	CONSTRAINT "program_tenant_id_key" UNIQUE("tenant_id","id")
);
--> statement-breakpoint
CREATE TABLE "project" (
	"id" text PRIMARY KEY NOT NULL,
	"tenant_id" text NOT NULL,
	"department_id" text NOT NULL,
	"program_id" text,
	"name" text NOT NULL,
	"client_name" text NOT NULL,
	"contract_type" text NOT NULL,
	"tz_offset_minutes" integer NOT NULL,
	"teirei_weekday" integer NOT NULL,
	"default_rate_jpy" integer NOT NULL,
	"eac_method" text NOT NULL,
	"calendar_jp" boolean NOT NULL,
	"calendar_vn" boolean NOT NULL,
	"demo_anchor" timestamp with time zone NOT NULL,
	"project_start" date,
	"project_finish" date,
	"data_date" date,
	CONSTRAINT "project_tenant_id_key" UNIQUE("tenant_id","id")
);
--> statement-breakpoint
CREATE TABLE "project_default_rate_entry" (
	"seq" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "project_default_rate_entry_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" text NOT NULL,
	"project_id" text NOT NULL,
	"effective_from" date NOT NULL,
	"yen_per_hour" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rate_entry" (
	"seq" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "rate_entry_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" text NOT NULL,
	"resource_id" text NOT NULL,
	"effective_from" date NOT NULL,
	"yen_per_hour" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "resource" (
	"id" text PRIMARY KEY NOT NULL,
	"tenant_id" text NOT NULL,
	"department_id" text NOT NULL,
	"name" text NOT NULL,
	"role" text NOT NULL,
	"tracker_account_ids" text[] NOT NULL,
	CONSTRAINT "resource_tenant_id_key" UNIQUE("tenant_id","id")
);
--> statement-breakpoint
CREATE TABLE "schedule_run" (
	"seq" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "schedule_run_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" text NOT NULL,
	"project_id" text NOT NULL,
	"prev_run_seq" bigint,
	"holiday_calendar_version_seq" bigint NOT NULL,
	"cause" text NOT NULL,
	"actor" text NOT NULL,
	"at" timestamp with time zone NOT NULL,
	"inputs" jsonb NOT NULL,
	"outputs" jsonb,
	"engine_version" text NOT NULL,
	"anchor" date,
	"computed_finish" date,
	"halted_reason" text,
	CONSTRAINT "schedule_run_project_seq_key" UNIQUE("tenant_id","project_id","seq")
);
--> statement-breakpoint
CREATE TABLE "session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	"active_tenant_id" text,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "tenant" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"currency" text DEFAULT 'JPY' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ticket_observation" (
	"id" text PRIMARY KEY NOT NULL,
	"tenant_id" text NOT NULL,
	"snapshot_id" text NOT NULL,
	"tracker_issue_id" text NOT NULL,
	"key" text NOT NULL,
	"title" text NOT NULL,
	"status_id" text NOT NULL,
	"resolved" boolean NOT NULL,
	"estimate_mh" bigint,
	"actual_mh" bigint,
	"assignee_account_id" text,
	"issue_type_id" text NOT NULL,
	"category_ids" text[] NOT NULL,
	"milestone_ids" text[] NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tracker_snapshot" (
	"seq" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "tracker_snapshot_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"id" text NOT NULL,
	"tenant_id" text NOT NULL,
	"connector_id" text NOT NULL,
	"observed_at" timestamp with time zone NOT NULL,
	"measurement_basis" text NOT NULL,
	"ticket_count" integer NOT NULL,
	CONSTRAINT "tracker_snapshot_tenant_id_key" UNIQUE("tenant_id","id")
);
--> statement-breakpoint
CREATE TABLE "verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "work_package" (
	"id" text PRIMARY KEY NOT NULL,
	"tenant_id" text NOT NULL,
	"project_id" text NOT NULL,
	"wbs_code" text NOT NULL,
	"name" text NOT NULL,
	"parent_id" text,
	"child_count" integer DEFAULT 0 NOT NULL,
	"is_leaf" boolean GENERATED ALWAYS AS (child_count = 0) STORED NOT NULL,
	"is_milestone" boolean NOT NULL,
	"is_catch_all" boolean NOT NULL,
	"duration_days" integer,
	"constraint_type" text DEFAULT 'asap' NOT NULL,
	"constraint_date" date,
	"planned_mh" bigint NOT NULL,
	"assigned_resource_ids" text[] NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "work_package_tenant_project_id_key" UNIQUE("tenant_id","project_id","id"),
	CONSTRAINT "work_package_leaf_key" UNIQUE("tenant_id","project_id","id","is_leaf"),
	CONSTRAINT "work_package_constraint_type_check" CHECK ("work_package"."constraint_type" IN ('asap', 'must_start_on', 'must_finish_on')),
	CONSTRAINT "work_package_leaf_only_inputs_check" CHECK (is_leaf OR (duration_days IS NULL AND constraint_type = 'asap' AND constraint_date IS NULL))
);
--> statement-breakpoint
CREATE TABLE "wp_dependency" (
	"seq" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "wp_dependency_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" text NOT NULL,
	"project_id" text NOT NULL,
	"predecessor_wp_id" text NOT NULL,
	"successor_wp_id" text NOT NULL,
	"type" text DEFAULT 'FS' NOT NULL,
	"lag_days" integer DEFAULT 0 NOT NULL,
	"pred_is_leaf" boolean DEFAULT true NOT NULL,
	"succ_is_leaf" boolean DEFAULT true NOT NULL,
	CONSTRAINT "wp_dependency_edge_key" UNIQUE("tenant_id","project_id","predecessor_wp_id","successor_wp_id"),
	CONSTRAINT "wp_dependency_type_check" CHECK ("wp_dependency"."type" = 'FS'),
	CONSTRAINT "wp_dependency_pred_is_leaf_check" CHECK ("wp_dependency"."pred_is_leaf" = true),
	CONSTRAINT "wp_dependency_succ_is_leaf_check" CHECK ("wp_dependency"."succ_is_leaf" = true)
);
--> statement-breakpoint
CREATE TABLE "wp_schedule" (
	"tenant_id" text NOT NULL,
	"project_id" text NOT NULL,
	"wp_id" text NOT NULL,
	"schedule_run_seq" bigint NOT NULL,
	"early_start" date,
	"early_finish" date,
	"late_start" date,
	"late_finish" date,
	"float_days" integer,
	"is_critical" boolean DEFAULT false NOT NULL,
	"state" text,
	"not_schedulable_reason" text,
	"stale" boolean DEFAULT false NOT NULL,
	CONSTRAINT "wp_schedule_pkey" PRIMARY KEY("tenant_id","project_id","wp_id"),
	CONSTRAINT "wp_schedule_state_check" CHECK ("wp_schedule"."state" IS NULL OR "wp_schedule"."state" IN ('complete', 'in_progress', 'remaining'))
);
--> statement-breakpoint
CREATE TABLE "wp_status_event" (
	"seq" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "wp_status_event_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"tenant_id" text NOT NULL,
	"project_id" text NOT NULL,
	"wp_id" text NOT NULL,
	"actual_start" date,
	"actual_finish" date,
	"source" text NOT NULL,
	"actor" text NOT NULL,
	"at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tenant_membership" (
	"user_id" text NOT NULL,
	"tenant_id" text NOT NULL,
	"role" text NOT NULL,
	"project_ids" text[] NOT NULL,
	CONSTRAINT "tenant_membership_user_id_tenant_id_pk" PRIMARY KEY("user_id","tenant_id")
);
--> statement-breakpoint
ALTER TABLE "actuals_ledger_entry" ADD CONSTRAINT "actuals_ledger_entry_connector_fk" FOREIGN KEY ("tenant_id","connector_id") REFERENCES "public"."connector"("tenant_id","id") MATCH FULL ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "actuals_ledger_entry" ADD CONSTRAINT "actuals_ledger_entry_tracker_snapshot_fk" FOREIGN KEY ("tenant_id","snapshot_id") REFERENCES "public"."tracker_snapshot"("tenant_id","id") MATCH FULL ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "actuals_ledger_entry" ADD CONSTRAINT "actuals_ledger_entry_baseline_version_fk" FOREIGN KEY ("tenant_id","active_baseline_version_seq") REFERENCES "public"."baseline_version"("tenant_id","seq") MATCH SIMPLE ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "baseline_version" ADD CONSTRAINT "baseline_version_project_fk" FOREIGN KEY ("tenant_id","project_id") REFERENCES "public"."project"("tenant_id","id") MATCH FULL ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "baseline_version" ADD CONSTRAINT "baseline_version_schedule_run_fk" FOREIGN KEY ("tenant_id","project_id","schedule_run_seq") REFERENCES "public"."schedule_run"("tenant_id","project_id","seq") MATCH FULL ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "baseline_wp" ADD CONSTRAINT "baseline_wp_baseline_version_fk" FOREIGN KEY ("tenant_id","project_id","baseline_version_seq") REFERENCES "public"."baseline_version"("tenant_id","project_id","seq") MATCH FULL ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "baseline_wp" ADD CONSTRAINT "baseline_wp_work_package_fk" FOREIGN KEY ("tenant_id","project_id","wp_id","wp_is_leaf") REFERENCES "public"."work_package"("tenant_id","project_id","id","is_leaf") MATCH FULL ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "connector" ADD CONSTRAINT "connector_project_fk" FOREIGN KEY ("tenant_id","project_id") REFERENCES "public"."project"("tenant_id","id") MATCH FULL ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "disposition_event" ADD CONSTRAINT "disposition_event_project_fk" FOREIGN KEY ("tenant_id","project_id") REFERENCES "public"."project"("tenant_id","id") MATCH FULL ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "disposition_event" ADD CONSTRAINT "disposition_event_work_package_fk" FOREIGN KEY ("tenant_id","project_id","wp_id") REFERENCES "public"."work_package"("tenant_id","project_id","id") MATCH SIMPLE ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "holiday_calendar_version" ADD CONSTRAINT "holiday_calendar_version_project_fk" FOREIGN KEY ("tenant_id","project_id") REFERENCES "public"."project"("tenant_id","id") MATCH FULL ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mapping_event" ADD CONSTRAINT "mapping_event_project_fk" FOREIGN KEY ("tenant_id","project_id") REFERENCES "public"."project"("tenant_id","id") MATCH FULL ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mapping_event" ADD CONSTRAINT "mapping_event_work_package_fk" FOREIGN KEY ("tenant_id","project_id","wp_id") REFERENCES "public"."work_package"("tenant_id","project_id","id") MATCH SIMPLE ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mapping_event" ADD CONSTRAINT "mapping_event_mapping_rule_fk" FOREIGN KEY ("tenant_id","project_id","rule_id") REFERENCES "public"."mapping_rule"("tenant_id","project_id","id") MATCH SIMPLE ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mapping_rule" ADD CONSTRAINT "mapping_rule_project_fk" FOREIGN KEY ("tenant_id","project_id") REFERENCES "public"."project"("tenant_id","id") MATCH FULL ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mapping_rule" ADD CONSTRAINT "mapping_rule_work_package_fk" FOREIGN KEY ("tenant_id","project_id","wp_id") REFERENCES "public"."work_package"("tenant_id","project_id","id") MATCH FULL ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "program" ADD CONSTRAINT "program_department_fk" FOREIGN KEY ("tenant_id","department_id") REFERENCES "public"."department"("tenant_id","id") MATCH FULL ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project" ADD CONSTRAINT "project_department_fk" FOREIGN KEY ("tenant_id","department_id") REFERENCES "public"."department"("tenant_id","id") MATCH FULL ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project" ADD CONSTRAINT "project_program_fk" FOREIGN KEY ("tenant_id","program_id") REFERENCES "public"."program"("tenant_id","id") MATCH SIMPLE ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project_default_rate_entry" ADD CONSTRAINT "project_default_rate_entry_project_fk" FOREIGN KEY ("tenant_id","project_id") REFERENCES "public"."project"("tenant_id","id") MATCH FULL ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rate_entry" ADD CONSTRAINT "rate_entry_resource_fk" FOREIGN KEY ("tenant_id","resource_id") REFERENCES "public"."resource"("tenant_id","id") MATCH FULL ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resource" ADD CONSTRAINT "resource_department_fk" FOREIGN KEY ("tenant_id","department_id") REFERENCES "public"."department"("tenant_id","id") MATCH FULL ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "schedule_run" ADD CONSTRAINT "schedule_run_project_fk" FOREIGN KEY ("tenant_id","project_id") REFERENCES "public"."project"("tenant_id","id") MATCH FULL ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "schedule_run" ADD CONSTRAINT "schedule_run_calendar_fk" FOREIGN KEY ("tenant_id","project_id","holiday_calendar_version_seq") REFERENCES "public"."holiday_calendar_version"("tenant_id","project_id","seq") MATCH FULL ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "schedule_run" ADD CONSTRAINT "schedule_run_prev_run_fk" FOREIGN KEY ("tenant_id","project_id","prev_run_seq") REFERENCES "public"."schedule_run"("tenant_id","project_id","seq") MATCH SIMPLE ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ticket_observation" ADD CONSTRAINT "ticket_observation_tracker_snapshot_fk" FOREIGN KEY ("tenant_id","snapshot_id") REFERENCES "public"."tracker_snapshot"("tenant_id","id") MATCH FULL ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tracker_snapshot" ADD CONSTRAINT "tracker_snapshot_connector_fk" FOREIGN KEY ("tenant_id","connector_id") REFERENCES "public"."connector"("tenant_id","id") MATCH FULL ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_package" ADD CONSTRAINT "work_package_project_fk" FOREIGN KEY ("tenant_id","project_id") REFERENCES "public"."project"("tenant_id","id") MATCH FULL ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "work_package" ADD CONSTRAINT "work_package_parent_fk" FOREIGN KEY ("tenant_id","project_id","parent_id") REFERENCES "public"."work_package"("tenant_id","project_id","id") MATCH SIMPLE ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "wp_dependency" ADD CONSTRAINT "wp_dependency_predecessor_fk" FOREIGN KEY ("tenant_id","project_id","predecessor_wp_id","pred_is_leaf") REFERENCES "public"."work_package"("tenant_id","project_id","id","is_leaf") MATCH FULL ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY DEFERRED;--> statement-breakpoint
ALTER TABLE "wp_dependency" ADD CONSTRAINT "wp_dependency_successor_fk" FOREIGN KEY ("tenant_id","project_id","successor_wp_id","succ_is_leaf") REFERENCES "public"."work_package"("tenant_id","project_id","id","is_leaf") MATCH FULL ON DELETE no action ON UPDATE no action DEFERRABLE INITIALLY DEFERRED;--> statement-breakpoint
ALTER TABLE "wp_schedule" ADD CONSTRAINT "wp_schedule_work_package_fk" FOREIGN KEY ("tenant_id","project_id","wp_id") REFERENCES "public"."work_package"("tenant_id","project_id","id") MATCH FULL ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "wp_schedule" ADD CONSTRAINT "wp_schedule_schedule_run_fk" FOREIGN KEY ("tenant_id","project_id","schedule_run_seq") REFERENCES "public"."schedule_run"("tenant_id","project_id","seq") MATCH FULL ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "wp_status_event" ADD CONSTRAINT "wp_status_event_work_package_fk" FOREIGN KEY ("tenant_id","project_id","wp_id") REFERENCES "public"."work_package"("tenant_id","project_id","id") MATCH FULL ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_idx" ON "account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "ledger_ticket_idx" ON "actuals_ledger_entry" USING btree ("ticket_id");--> statement-breakpoint
CREATE INDEX "baseline_wp_work_package_idx" ON "baseline_wp" USING btree ("tenant_id","project_id","wp_id","wp_is_leaf");--> statement-breakpoint
CREATE INDEX "identity_event_user_idx" ON "identity_event" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "mapping_ticket_idx" ON "mapping_event" USING btree ("ticket_id");--> statement-breakpoint
CREATE INDEX "program_department_idx" ON "program" USING btree ("department_id");--> statement-breakpoint
CREATE INDEX "project_program_idx" ON "project" USING btree ("program_id");--> statement-breakpoint
CREATE INDEX "session_user_idx" ON "session" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "obs_snapshot_idx" ON "ticket_observation" USING btree ("snapshot_id");--> statement-breakpoint
CREATE INDEX "verification_identifier_idx" ON "verification" USING btree ("identifier");--> statement-breakpoint
CREATE INDEX "wp_project_idx" ON "work_package" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "wp_dependency_successor_idx" ON "wp_dependency" USING btree ("tenant_id","project_id","successor_wp_id","succ_is_leaf");--> statement-breakpoint
CREATE INDEX "wp_status_event_wp_idx" ON "wp_status_event" USING btree ("tenant_id","project_id","wp_id","seq");