-- Story 1.2 watermark slice, founder decision D1: `mapping_event.seq` and
-- `actuals_ledger_entry.seq` become `GENERATED BY DEFAULT AS IDENTITY`. EXPAND-ONLY (AD-19): the
-- columns keep their values, and a caller that still writes an explicit `seq` (the seed, with
-- OVERRIDING SYSTEM VALUE) still can. The `momo_next_*_seq()` allocators the caller used before
-- are no longer generated; a database that already has them keeps them, unused and harmless,
-- until a later contract step drops them.
--
-- Generated by `drizzle-kit generate` (0.31.10) from packages/db/src/schema.ts, then HAND-EDITED
-- in exactly one way: the two DO blocks at the end, which set each new identity counter to the
-- column's current MAX(seq) with is_called = true, so the first identity default is MAX(seq) + 1
-- and cannot re-issue a `seq` a row already holds. is_called must be true on a non-empty table:
-- with it false, `pg_sequence_last_value` reads NULL, and the seed's `syncIdentitySequences`
-- (whose MAX sees only one Tenant under FORCE RLS) could then rewind the counter below another
-- Tenant's rows. MAX must see EVERY Tenant's rows, and FORCE row-level security applies to the
-- owner running this migration, so each block lifts FORCE for its one statement and restores it
-- only if it was set. On an empty table the counter is set to 1 with is_called = false, so the
-- first default is 1.
ALTER TABLE "actuals_ledger_entry" ALTER COLUMN "seq" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "actuals_ledger_entry_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "mapping_event" ALTER COLUMN "seq" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "mapping_event_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);
--> statement-breakpoint
DO $$
DECLARE forced boolean; top bigint;
BEGIN
  SELECT relforcerowsecurity INTO forced FROM pg_catalog.pg_class
   WHERE oid = 'public.actuals_ledger_entry'::regclass;
  ALTER TABLE public."actuals_ledger_entry" NO FORCE ROW LEVEL SECURITY;
  SELECT MAX(seq) INTO top FROM public."actuals_ledger_entry";
  PERFORM setval(pg_get_serial_sequence('public.actuals_ledger_entry', 'seq'),
                 GREATEST(COALESCE(top, 0), 1), top IS NOT NULL);
  IF forced THEN
    ALTER TABLE public."actuals_ledger_entry" FORCE ROW LEVEL SECURITY;
  END IF;
END $$;
--> statement-breakpoint
DO $$
DECLARE forced boolean; top bigint;
BEGIN
  SELECT relforcerowsecurity INTO forced FROM pg_catalog.pg_class
   WHERE oid = 'public.mapping_event'::regclass;
  ALTER TABLE public."mapping_event" NO FORCE ROW LEVEL SECURITY;
  SELECT MAX(seq) INTO top FROM public."mapping_event";
  PERFORM setval(pg_get_serial_sequence('public.mapping_event', 'seq'),
                 GREATEST(COALESCE(top, 0), 1), top IS NOT NULL);
  IF forced THEN
    ALTER TABLE public."mapping_event" FORCE ROW LEVEL SECURITY;
  END IF;
END $$;
