/**
 * The keys `pnpm dev` needs, and where they come from (story 1.1 slice B3, founder decision Q1-A).
 *
 * On the first run there is no root `.env.local`, so one is generated: the two docker compose
 * connection strings, a random `BETTER_AUTH_SECRET`, a random `SEED_DEMO_PASSWORD` and the web
 * origin. Later runs read that file. A key set in the shell wins over the file. The file is never
 * rewritten — delete it to regenerate it.
 *
 * This module is pure: it is handed the shell's environment, the file's text (or `null`) and a
 * source of random bytes, and it returns the resolved environment plus the text to write, if any.
 * The caller does the reading and the writing. `packages/app/src/config.ts` still validates every
 * key in the children; nothing here is a default the schema could fall back on.
 */

export const LOCAL_ENV_FILE = '.env.local';

export const DEFAULT_WEB_PORT = 3101;

/** Every key the run needs, checked before compose starts. */
export const REQUIRED_KEYS = [
  'DATABASE_URL',
  'APP_DATABASE_URL',
  'SEED_DEMO_PASSWORD',
  'BETTER_AUTH_SECRET',
  'BETTER_AUTH_URL',
] as const;

export const COMPOSE_DATABASE_URL = 'postgres://momo:momo@localhost:55433/momo_keikaku';
export const COMPOSE_APP_DATABASE_URL =
  'postgres://momo_app:momo_app@localhost:55433/momo_keikaku';

/** The two demo users the seed creates (`packages/db/src/seed.ts`). */
export const DEMO_EMAILS = ['linh@momo-digital.example', 'hoang@momo-digital.example'] as const;

/** 36 bytes → 48 base64url characters: above Better Auth's 32-character floor. */
const SECRET_BYTES = 36;
/** 12 bytes → 16 base64url characters: above the seed's 8-character floor. */
const PASSWORD_BYTES = 12;

export type Env = Readonly<Record<string, string | undefined>>;
export type RandomBytes = (size: number) => Uint8Array;

export interface ResolvedDevEnv {
  /** The shell's environment with the file's keys filled in underneath it. */
  readonly env: Env;
  /** The text of a newly generated `.env.local`, or `null` when one already exists. */
  readonly fileToWrite: string | null;
}

function base64url(bytes: Uint8Array): string {
  return Buffer.from(bytes).toString('base64url');
}

/**
 * Reads `KEY=VALUE` lines. Blank lines and `#` comments are skipped, an optional `export ` prefix
 * is dropped, and one pair of matching surrounding quotes is removed from the value.
 */
export function parseEnvFile(text: string): Readonly<Record<string, string>> {
  const entries: [string, string][] = [];
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (line === '' || line.startsWith('#')) continue;
    const body = line.startsWith('export ') ? line.slice('export '.length).trimStart() : line;
    const eq = body.indexOf('=');
    if (eq <= 0) continue;
    const key = body.slice(0, eq).trim();
    const value = body.slice(eq + 1).trim();
    const quoted = /^(['"])(.*)\1$/.exec(value);
    entries.push([key, quoted ? quoted[2] : value]);
  }
  return Object.fromEntries(entries);
}

/** The text of a freshly generated `.env.local`. */
export function generateEnvFile(randomBytes: RandomBytes, port: number): string {
  return [
    '# Generated by `pnpm dev` on its first run (story 1.1, decision Q1-A). Local only — gitignored.',
    '# `pnpm dev` never rewrites this file: delete it to generate new values.',
    '# A key exported in the shell wins over the value here.',
    `DATABASE_URL=${COMPOSE_DATABASE_URL}`,
    `APP_DATABASE_URL=${COMPOSE_APP_DATABASE_URL}`,
    `BETTER_AUTH_SECRET=${base64url(randomBytes(SECRET_BYTES))}`,
    `SEED_DEMO_PASSWORD=${base64url(randomBytes(PASSWORD_BYTES))}`,
    `BETTER_AUTH_URL=http://localhost:${port}`,
    '',
  ].join('\n');
}

/**
 * Resolves the run's environment. A non-empty shell value wins; otherwise the file's value is
 * used. With no file, one is generated and returned as `fileToWrite`; an existing file is never
 * returned for rewriting, even when it lacks a key (the missing-key check names it instead).
 */
export function resolveDevEnv(
  processEnv: Env,
  existingFileText: string | null,
  randomBytes: RandomBytes,
  port: number = DEFAULT_WEB_PORT,
): ResolvedDevEnv {
  const fileToWrite = existingFileText === null ? generateEnvFile(randomBytes, port) : null;
  const fileValues = parseEnvFile(existingFileText ?? fileToWrite ?? '');
  const fromFile = Object.fromEntries(
    Object.entries(fileValues).filter(([key]) => !processEnv[key]),
  );
  return { env: { ...processEnv, ...fromFile }, fileToWrite };
}

/** The required keys the resolved environment still lacks. */
export function missingKeys(env: Env): readonly string[] {
  return REQUIRED_KEYS.filter((key) => !env[key]);
}
